/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    LC3: typeof import('./src/components/LC3.vue')['default']
    MdiPause: typeof import('~icons/mdi/pause')['default']
    MdiPlay: typeof import('~icons/mdi/play')['default']
    MdiStepForward: typeof import('~icons/mdi/step-forward')['default']
    Slider: typeof import('primevue/slider')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
