/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    LC3: typeof import('./src/components/LC3.vue')['default']
    MdiHomeOutline: typeof import('~icons/mdi/home-outline')['default']
    MdiInformationOutline: typeof import('~icons/mdi/information-outline')['default']
    MdiPause: typeof import('~icons/mdi/pause')['default']
    MdiPlay: typeof import('~icons/mdi/play')['default']
    MdiStepBackward: typeof import('~icons/mdi/step-backward')['default']
    MdiStepForward: typeof import('~icons/mdi/step-forward')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Pseudocode: typeof import('./src/components/Pseudocode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiGithub: typeof import('~icons/simple-icons/github')['default']
    SiteNav: typeof import('./src/components/SiteNav.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
